### ISSUE TITLE
progressBar

### ISSUE THREAD

**Issue by QKai0314** [londonappbrewery/Quizzler-iOS12#4]
progressBar can not update with xcode 11.0

**Comment by pop-goes-the-Weasel** [comment]
did you solve this?

**Comment by pop-goes-the-Weasel** [comment]
@angelabauer ?

**Comment by MarinaRomanova** [comment]
set .translatesAutoresizingMaskIntoConstraints 's of the view to YES
[see this](https://stackoverflow.com/questions/57597413/ios-13-animating-view-not-changing-frame)
